security:
    encoders:
        ps\lieuxBundle\EntitysControlers\user\User:
            algorithm: plaintext
    providers:
        my_datastore_provider:
            id: pslieux.autentification.provider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main_login:
            pattern:   ^/login$
            anonymous: true

        main:
            pattern: ^/
            anonymous: false
            provider: my_datastore_provider
            form_login:
                login_path: login
                check_path: login_check
            logout:
                path: logout
                target: login

        default:
            anonymous: ~