index:
    path:     /
    defaults: { _controller: pslieuxBundle:lieu:index }

list:
    path:     /lieu/list
    defaults: { _controller: pslieuxBundle:lieu:list }

get:
    path:     /lieu/{id}
    defaults: { _controller: pslieuxBundle:lieu:get }

delete:
    path:     /lieu/delete/{id}
    defaults: { _controller: pslieuxBundle:lieu:delete }

create:
    path:     /lieu/create/
    defaults: { _controller: pslieuxBundle:lieu:create }

edit:
    path:     /lieu/edit/{id}
    defaults: { _controller: pslieuxBundle:lieu:edit }

login:
    path: /login
    defaults:
        _controller: pslieuxBundle:lieu:login

login_check:
    path: /login_check

logout:
    path: /logout