index:
    path:     /
    defaults: { _controller: pslieuxBundle:lieu:index }

list:
    path:     /list
    defaults: { _controller: pslieuxBundle:lieu:list }

get:
    path:     /etab/{id}
    defaults: { _controller: pslieuxBundle:lieu:get }

delete:
    path:     /etab/delete/{id}
    defaults: { _controller: pslieuxBundle:lieu:delete }

create:
    path:     /etab/create/
    defaults: { _controller: pslieuxBundle:lieu:create }

edit:
    path:     /etab/edit/{id}
    defaults: { _controller: pslieuxBundle:lieu:edit }