<?php

namespace ps\lieuxBundle\Repository\lieu;

/**
 * UserEtabRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserEtabRepository extends \Doctrine\ORM\EntityRepository
{
}
